# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  an_env_var: an_env_value

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: msarahan/workflow-env-var-demo/.github/workflows/child.yml@main
    with:
      example: ${{ env.an_env_var }}
