# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  an_env_var: an_env_value

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  child-call:
    uses: msarahan/workflow-env-var-demo/.github/workflows/child.yml@main
    with:
      example: ${{ env.an_env_var }}
  jobby-mcjobface:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.an_env_var }}
        shell: bash
      - run: echo ${an_env_var}
        shell: bash
  
